platform :ios, '13.0'

target 'MercadoLibre' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MercadoLibre
	pod 'SDWebImage', '~> 5.0'


  target 'MercadoLibreTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
